[mypy]
python_version = 3.11
ignore_missing_imports = True
disable_error_code = import-untyped
namespace_packages = False
mypy_path = src
ignore_errors = True
warn_unused_ignores = False
warn_redundant_casts = False
warn_unused_configs = False
show_error_codes = True
exclude = (_local_tmp|_pytest_local_tmp|_pytest_tmp|\.pytest_cache|tests/\.tmp|tests/pytest-cache-files-)
